pipeline {
    agent any
    tools {
        jdk 'myjava'
        maven 'mymaven'
    }
    stages {
        stage('Clone') {
            steps {
                echo "checking out the repository"
                git 'https://github.com/mrathne/pipelinecode.git'
            
            }
        }
        stage('build'){
            steps {
                echo "building the project"
                sh "cd MavenProject ; mvn clean install ; pwd"
            }
        }
        
        stage('Archieve Artifacts'){
            steps {
                echo "archiving the artifacts"
                archiveArtifacts 'MavenProject/multi3/target/*.war'
            }
            
        }

        stage('Deployment') {
            // Deployment
            steps {
                script {
                    echo "deployment"
                    sh 'chmod -R 755 MavenProject/multi3/target/'
                    sh 'cp MavenProject/multi3/target/*.war /home/centos/Tomcat8/apache-tomcat-8.0.9/webapps/'
                }
            }
        }
		
        stage('publish html report') {
            steps{
                echo "publishing the html report"
                publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, keepAll: false, reportDir: '', reportFiles: 'index.html', reportName: 'HTML Report', reportTitles: ''])
            }
        }
        stage("Metrics"){
            steps{
				parallel ( "Cobertura Report":   
				{ 
				  node('window'){
					git 'https://github.com/mrathne/pipelinecode.git'
					sh "cd MavenProject ; mvn cobertura:cobertura -Dcobertura.report.format=xml ; pwd"
			      }
				},
				"FindBugs Report" : {
					node('window'){
						sh "chmod -R 777 ../"
						sh "echo $workspace"
						sh "mkdir findbug ; cd findbug ;pwd"
						git 'https://github.com/mrathne/pipelinecode.git'
						sh "cd MavenProject ; mvn findbugs:findbugs ; pwd"
						deleteDir()
					}
		       })
            }
			 post{
					success {
						emailext body: 'Successfully completed pipeline project with archiving the artifacts', subject: 'Pipeline was successfull', to: '$emailrecepientlist'
					}
			}
		}
		stage('clean up') {
				steps {
					echo "cleaning up the workspace"
					cleanWs()
				}
		}       
    }
}
